databases:
  - name: nyumba
    databaseName: nyumba
    user: nyumba

services:
  - type: web
    name: nyumba
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn nyumba.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: nyumba
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4